---
- name: Postgresql | Ensure databases
  become: yes
  become_user: postgres
  postgresql_db:
    name: "{{ item.name }}"
    owner: "{{ item.owner }}"
    encoding: "{{ item.encoding | default('UTF-8') }}"
    lc_collate: "{{ item.lc_collate | default('en_US.UTF-8') }}"
    lc_ctype: "{{ item.lc_ctype | default('en_US.UTF-8') }}"
    conn_limit: "{{ item.connection_limit | default('-1') }}"
    template: template0
  with_items: "{{ postgresql.databases }}"

- name: Postgresql | Ensure DB owners privileges
  become: yes
  become_user: postgres
  postgresql_privs:
    # posgres here is only DB to connect to, not a DB to which privs
    # will be granted
    db: postgres
    privs: ALL
    type: database
    obj: "{{ item.name }}"
    role: "{{ item.owner }}"
  with_items: "{{ postgresql.databases }}"
