---
- name: Postgresql | List available clusters
  shell:
    cmd: |
      pg_lsclusters -h | cut -f2 -d ' '
  register: clusters_available
  changed_when: false

- name: Postgresql | Drop not needed clusters
  command: "pg_dropcluster --stop {{ postgresql.version }} {{ item }}"
  when: clusters_available.stdout is match(item)
  with_items: "{{ postgresql.clusters_to_drop }}"

  # Postgres typical locale name is en_US.utf8 but system locale name looks
  # like en_US.UTF-8, so we're doing a little trick here
- name: Postgresql | Generate proper locales
  locale_gen:
    name: '{{ item.locale.split(".")[0] }}.UTF-8'
    state: present
  when: item.locale is defined and "utf" in item.locale
  with_items: "{{ postgresql.clusters_to_create }}"

- name: Postgresql | Create needed cluster
  shell:
    cmd: |
      pg_createcluster --locale {{ item.locale | default("en_US.utf8") }} \
                       --start {{ item.version | default(postgresql.version) }} \
                       {{ item.name }}
  with_items: "{{ postgresql.clusters_to_create }}"
  when: clusters_available.stdout is not match(item.name)

- name: Ensure needed service is started
  systemd:
    state: started
    name: 'postgresql@{{ postgresql.version }}-main.service'
  when: not postgresql.clusters_to_create

- name: Ensure needed service is started
  systemd:
    state: started
    name: 'postgresql@{{ item.version|default(postgresql.version) }}-{{ item.name|default("main") }}.service'
  with_items: "{{ postgresql.clusters_to_create }}"
