---
- name: Postgresql | List available clusters
  shell:
    cmd: |
      pg_lsclusters -h | cut -f2 -d ' '
  register: clusters_available
  changed_when: false

- name: Postgresql | Drop not needed clusters
  command: "pg_dropcluster --stop {{ postgresql.version }} {{ item }}"
  when: clusters_available.stdout is match(item)
  with_items: "{{ postgresql.clusters_to_drop }}"

- name: Postgresql | Create needed cluster
  shell:
    cmd: |
      pg_createcluster --locale {{ item.locale | default("en_US.utf8") }} \
                       --start {{ item.version | default(postgresql.version) }} \
                       {{ item.name }}
  with_items: "{{ postgresql.clusters_to_create }}"
  when: clusters_available.stdout == "" or clusters_available.stdout is not match(item.name)
