---
- name: Postgresql | Add repo key
  apt_key:
    url: "{{ postgresql.repo_key_url }}"
    state: present

- name: Postgresql | Add sources deb repository
  apt_repository:
    repo: "deb {{ postgresql.repository_url }} {{ os_release }}-pgdg {{ postgresql.repo_type }}"
    state: present
    filename: postgresql

- name: Postgresql | Update cache
  apt:
    update_cache: yes
