---
- name: Converge
  hosts: all
  become: true

  vars:
    postgresql:
      enabled: yes
      install_from_sources: yes
      version: 12
      additional_packages:
        - libpq-dev
        - python3-psycopg2
        - postgresql-client-12
      clusters_to_drop: []
      users:
        - name: user
          secret: password
          state: present
      databases:
        - name: testdb
          owner: user

  pre_tasks:
    # The Fedora 30+ container images have only C.UTF-8 installed
    - name: Update apt cache.
      apt: update_cache=true cache_valid_time=600
      changed_when: false
      when: ansible_os_family == 'Debian'

  roles:
    - role: postgresql

#  post_tasks:
#    - name: Verify postgres is running.
#      command: "{{ postgresql_bin_path }}/pg_ctl -D {{ postgresql_data_dir }} status"
#      changed_when: false
#      become: true
#      become_user: postgres
